export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const INCREMENT_COUNTER_ASYNC = 'INCREMENT_COUNTER_ASYNC';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE';
export const LOAD_DATA = 'LOAD_DATA';