export const INCREAMENT_COUNTER="INCREAMENT_COUNTER";
export const INCREAMENT_COUNTER_TEXT="INCREAMENT_COUNTER_TEXT";
export const DECREAMENT_COUNTER="DECREAMENT_COUNTER";
export const DECREAMENT_COUNTER_TEXT="DECREAMENT_COUNTER_TEXT";
export const RESET_COUNTER="RESET_COUNTER";